# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wakatime.CLIWakatime
PackageVersion: 2.26.15
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-386.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.26.15/wakatime-cli-windows-386.zip
  InstallerSha256: DDC6B30654D660FEC50B9877771EE8D026D2C3320AD97EFF97102F78298CDCC1
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-amd64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.26.15/wakatime-cli-windows-amd64.zip
  InstallerSha256: 9ECF278ADDC309F242D90AAE39821AB303A93605924B9EF10D2CD815986B53C8
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-arm64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.26.15/wakatime-cli-windows-arm64.zip
  InstallerSha256: A38974661480AE6316281041F34E08BA82D84BC1934935E02BEAFE13A8898E31
ManifestType: installer
ManifestVersion: 1.12.0
