# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.VCFMerger
PackageVersion: 1.0.0.0
InstallerLocale: en-US
Installers:
- InstallerUrl: https://files.vovsoft.com/vcf-merger.exe
  Architecture: x86
  InstallerSha256: 0F80F9C031FD5E3BA93CA623877BF711621B14806C987EC2C563EF992AF16F9B
  InstallerType: inno
  Scope: machine
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  ProductCode: VCF Merger_is1
  AppsAndFeaturesEntries:
  - ProductCode: VCF Merger_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\VCF Merger'
  FileExtensions:
  - VCF
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: vcfmerger.exe
    PortableCommandAlias: vcfmerger
  InstallerUrl: https://files.vovsoft.com/vcf-merger-portable.zip
  InstallerSha256: 6C3CB8B350875AFAE95DC35BD6146A3A85E96000358B88466C3234C107C6F2CA
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2025-07-12
