# Created with YamlCreate.ps1 v2.1.2 $debug=NVS1.7-2-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NirSoft.DownTester
PackageVersion: "1.30"
InstallerLocale: en-US
ReleaseDate: 2013-06-12
Installers:
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/downtester_setup.exe
  InstallerSha256: F12AD4298D0DC217A5A3C2A1D080D3575000D599F5468DB91F1979761AB0DA1E
  InstallerType: nullsoft
  Scope: machine
  InstallModes:
  - interactive
  - silent
  UpgradeBehavior: install
  ProductCode: NirSoft DownTester
  AppsAndFeaturesEntries:
  - DisplayName: NirSoft DownTester
    ProductCode: NirSoft DownTester
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\NirSoft\DownTester'
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/downtester.zip
  InstallerSha256: 15D6A3ECEA7AB676769042CFDB3CBBEA197F81BE63AEC409E792DD2258642FE2
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: DownTester.exe
    PortableCommandAlias: DownTester
ManifestType: installer
ManifestVersion: 1.12.0
