# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.ImageSplitter
PackageVersion: 1.4.0.0
InstallerLocale: en-US
Installers:
- InstallerUrl: https://files.vovsoft.com/image-splitter.exe
  Architecture: x64
  InstallerSha256: B126DEB69B7AA50A0C8024D1FB4374FD15BD1E0CA3D8300D4EAD94767E76DF58
  InstallerType: inno
  Scope: machine
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  ProductCode: Image Splitter_is1
  AppsAndFeaturesEntries:
  - ProductCode: Image Splitter_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\Image Splitter'
  FileExtensions:
  - BMP
  - GIF
  - JPEG
  - PNG
  - TIFF
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: imagesplitter.exe
    PortableCommandAlias: imagesplitter
  InstallerUrl: https://files.vovsoft.com/image-splitter-portable.zip
  InstallerSha256: A1F5B9BCBA58294312B1DC027713CEAAA1CE8A307FCB16904FA8B1A9C38DF006
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2025-10-05
