# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: NirSoft.USBLogView
PackageVersion: "1.26"
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
