# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wakatime.CLIWakatime
PackageVersion: 2.27.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-386.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.27.1/wakatime-cli-windows-386.zip
  InstallerSha256: 99F93CE418FDB4189D66F298B452EBA4C1B46B6D97A7EDFA4C481A94D17E101C
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-amd64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.27.1/wakatime-cli-windows-amd64.zip
  InstallerSha256: 0D8FBE97540F50B4B9675185E0DD35DA1DAC5C3996894634AA7D772E8B8C2752
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: wakatime-cli-windows-arm64.exe
    PortableCommandAlias: wakatime-cli
  InstallerUrl: https://github.com/wakatime/wakatime-cli/releases/download/v2.27.1/wakatime-cli-windows-arm64.zip
  InstallerSha256: B7B132F14F7F943ACCCD267A25DC1DD82345EED99C54F0F5717910C43F4F126B
ManifestType: installer
ManifestVersion: 1.12.0
