# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NirSoft.Volumouse
PackageVersion: '2.20'
InstallerLocale: en-US
ReleaseDate: 2025-04-07
Installers:
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/volumouse_setup.exe
  InstallerSha256: 54FB9461FFC0156E0DA119E045510466262DE081ED3C4D863B27E620FB471BF4
  InstallerType: nullsoft
  Scope: machine
  InstallModes:
  - interactive
  - silent
  UpgradeBehavior: install
  ProductCode: Volumouse
  AppsAndFeaturesEntries:
  - DisplayName: NirSoft Volumouse
    ProductCode: Volumouse
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\NirSoft\Volumouse'
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/volumouse.zip
  InstallerSha256: B64BD32B697D36F2435227FDF728EF844437CEDAAEA1ED016E82FC4EC03AA744
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: volumouse.exe
    PortableCommandAlias: volumouse
- Architecture: x64
  InstallerUrl: https://www.nirsoft.net/utils/volumouse-x64.zip
  InstallerSha256: B28AEA3C7321936A9BC6CEC09D445477DD0BFB3CF3B0C31C149210D40D266A98
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: volumouse.exe
    PortableCommandAlias: volumouse
ManifestType: installer
ManifestVersion: 1.12.0
