# Created with YamlCreate.ps1 v2.1.2 $debug=NVS1.7-2-4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NirSoft.IPNetInfo
PackageVersion: "1.95"
InstallerLocale: en-US
ReleaseDate: 2020-02-14
Installers:
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/ipnetinfo_setup.exe
  InstallerSha256: F59C71CB1052BA66D3FE01CDBAC717491A5A0340B11D813AE35A16E1EFCB92B1
  InstallerType: nullsoft
  Scope: machine
  InstallModes:
  - interactive
  - silent
  UpgradeBehavior: install
  ProductCode: NirSoft IPNetInfo
  AppsAndFeaturesEntries:
  - DisplayName: NirSoft IPNetInfo
    ProductCode: NirSoft IPNetInfo
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\NirSoft\IPNetInfo'
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/ipnetinfo.zip
  InstallerSha256: F3DB23A0E915F490A00B8D241BC8F2524C67EBAFB37B6D28939CB7BBA11EA399
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: IPNetInfo.exe
    PortableCommandAlias: IPNetInfo
ManifestType: installer
ManifestVersion: 1.12.0
