# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: EXEMSI.MSIWrapper
PackageVersion: 4.0.41.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{C676C11E-0C18-4BD6-AADC-0655D1DBA415}'
ReleaseDate: 2013-05-14
AppsAndFeaturesEntries:
- DisplayName: MSI Wrapper 4.0.41.0
  ProductCode: '{C676C11E-0C18-4BD6-AADC-0655D1DBA415}'
  UpgradeCode: '{D9622D4D-2942-4866-B7A7-28B83645FBE6}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\MSI Wrapper'
Installers:
- Architecture: x86
  InstallerUrl: https://www.exemsi.com/downloads/msi_wrapper/MSI_Wrapper_4_0_41_0.msi
  InstallerSha256: CA15E4B7121627D0F86A910302F5364730D16A0472020F6B4D68EC3B40A67EE9
ManifestType: installer
ManifestVersion: 1.10.0
