# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.JSONBeautifier
PackageVersion: 2.0.0.0
InstallerLocale: en-US
Installers:
- InstallerUrl: https://files.vovsoft.com/json-beautifier.exe
  Architecture: x64
  InstallerSha256: E50E7AA7BD428FFE00444DDABB2B4ADF99DA5505F3C90D0A97E15D512E3ED001
  InstallerType: inno
  Scope: machine
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  ProductCode: JSON Beautifier_is1
  AppsAndFeaturesEntries:
  - ProductCode: JSON Beautifier_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\JSON Beautifier'
  FileExtensions:
  - JSON
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: jsonbeautifier.exe
    PortableCommandAlias: jsonbeautifier
  InstallerUrl: https://files.vovsoft.com/json-beautifier-portable.zip
  InstallerSha256: C05CD630D656D36D783C37CD5BBAA6426FE3B4898527AA3464C870426CDF3AF9
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-01-02
