# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NirSoft.VideoCacheView
PackageVersion: '3.11'
InstallerLocale: en-US
ReleaseDate: 2025-01-31
Installers:
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/videocacheview_setup.exe
  InstallerSha256: AB838F8026F761D4E6D02C90B486B8B9B2FDA8EA4D32F2C04ADC4DFCA56AC8BA
  InstallerType: nullsoft
  Scope: machine
  InstallModes:
  - interactive
  - silent
  UpgradeBehavior: install
  ProductCode: NirSoft VideoCacheView
  AppsAndFeaturesEntries:
  - DisplayName: NirSoft VideoCacheView
    ProductCode: NirSoft VideoCacheView
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\NirSoft\VideoCacheView'
- Architecture: x86
  InstallerUrl: https://www.nirsoft.net/utils/videocacheview.zip
  InstallerSha256: C62BB5338B7DCE2B84DF62A0847B8922DDF3BC0384A2BBCE483A86C04C49CCF7
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: VideoCacheView.exe
    PortableCommandAlias: VideoCacheView
- Architecture: x64
  InstallerUrl: https://www.nirsoft.net/utils/videocacheview-x64.zip
  InstallerSha256: 5441EE47081C0D91A2BDC4781B54E0D896FA093B443A065255E2C47F4C1EF446
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: VideoCacheView.exe
    PortableCommandAlias: VideoCacheView
ManifestType: installer
ManifestVersion: 1.12.0
