# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.TimeSync
PackageVersion: 3.2.0.0
InstallerLocale: en-US
Installers:
- InstallerUrl: https://files.vovsoft.com/time-sync.exe
  Architecture: x86
  InstallerSha256: B9CE2BF5CEC9D6377E362BEDFB241CD2499182BFC8984A8E3C3EC7E8647115AE
  InstallerType: inno
  Scope: machine
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  ProductCode: Time Sync_is1
  AppsAndFeaturesEntries:
  - ProductCode: Time Sync_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\Time Sync'
  Protocols:
  - SNTP
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: timesync.exe
    PortableCommandAlias: timesync
  InstallerUrl: https://files.vovsoft.com/time-sync-portable.zip
  InstallerSha256: 986C4D38C2BBF45B90AD521DED3201C2C0F337CEC67739C4CD7FDD331E4B4EBD
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-02-25
